config/routes.rb
Rails.application.routes.draw do

  # get 'password_resets/new'
  #
  # get 'password_resets/edit'

  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord

  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  validates(:name, {presence: true, length: {maximum: 50}})

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates(:email, {presence: true, length: {maximum: 255}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}})

  validates(:password, {presence: true, length: {minimum: 6}, allow_nil: true})

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(
      reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now
    )
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  private
    def downcase_email
      email.downcase!
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    # @users = User.all
    # @users = User.paginate(page: params[:page])
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
      # log_in @user
      # flash[:success] = "Hello #{@user.name}. Welcome to the Sample App!"
      # redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 150})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "button is-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow-form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :name, class: "label" %>
    <div class="control has-icons-left">
      <%= f.text_field :name, class: "input" %>
      <span class="icon is-small is-left">
        <i class="fas fa-user"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <%= f.label :email, class: "label" %>
    <div class="control has-icons-left">
      <%= f.email_field :email, class: "input" %>
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <%= f.label :password, class: "label" %>
    <div class="control has-icons-left">
      <%= f.password_field :password, class: "input" %>
      <span class="icon is-small is-left">
        <i class="fas fa-lock"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Confirmation", class: "label" %>
    <div class="control has-icons-left">
      <%= f.password_field :password_confirmation, class: "input" %>
      <span class="icon is-small is-left">
        <i class="fas fa-check"></i>
      </span>
    </div>
  </div>

  <%= f.submit yield(:button_text), class: "button is-primary width-100" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "button is-primary is-outlined" %>
<% end %>

app/views/users/_user.html.erb
<!-- <div class="box"> -->
  <div class="media">
    <div class="media-left">
      <%= gravatar_for user, size: 50 %>
    </div>
    <div class="media-content">
      <p class="title is-4"><%= link_to user.name, user %></p>
      <p class="subtitle is-6"><%= user.email %></p>
    </div>
  </div>
<!-- </div> -->

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1 class="title is-1 has-text-centered">Update your profile</h1>
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
    <!-- <%= form_for(@user, url: edit_user_path) do |f| %> -->
      <%= render 'form' %>
    <!-- <% end %> -->

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1 class="title">All users</h1>
<div class="pagination-wrapper">
  <%= will_paginate %>
</div>
<div class="columns is-multiline">
  <% @users.each do |user| %>
  <div class="column is-4">
    <div class="box">
      <div class="media">
        <div class="media-left">
          <%= gravatar_for user, size: 50 %>
        </div>
        <div class="media-content">
          <p class="title is-4"><%= link_to user.name, user %></p>
          <p class="subtitle is-6"><%= user.email %></p>
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "delete", user, method: :delete, data: {confirm: "You sure?"}, class: "button is-danger is-outlined is-small" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="pagination-wrapper">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1 class="title is-1 has-text-centered">Sign up</h1>
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
    <!-- <%= form_for(@user, url: signup_path) do |f| %> -->
      <%= render 'form' %>
    <!-- <% end %> -->
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="columns">
  <div class="column">
    <div class="profile-box">
      <div class="columns">
        <div class="column is-one-third">
          <div class="box-user-image">
            <%= gravatar_for @user %>
          </div>
          <div class="box-user-info">
            <h1 class="title"><%= @user.name %></h1>
            <p class="subtitle"><%= @user.email %></p>
            <h2>Microposts (<%= @user.microposts.count %>)</h2>
          </div>
          <div class="stats">
            <%= render 'shared/stats' %>
          </div>
          <%= render 'follow_form' if logged_in? %>
        </div>
        <% if @user.microposts.any? %>
        <div class="column microposts">
          <div class="microposts-list">
            <%= render @microposts %>
          </div>
          <div class="pagination-wrapper">
            <%= will_paginate @microposts %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="columns">
  <div class="column">
    <div class="profile-box">
      <div class="columns">
        <div class="column is-one-third">
          <div class="card-wrapper">
            <div class="card">
              <div class="card-content user-info">
                <%= render 'shared/user_info' %>
              </div>
              <div class="card-footer stats">
                <%= render 'shared/stats' %>
              </div>
            </div>
            <% if @users.any? %>
            <div class="user-avatars">
              <% @users.each do |user| %>
              <%= link_to gravatar_for(user, size: 35), user %>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="column users-follow">
          <h3 class="title is-4"><%= @title %></h3>
          <% if @users.any? %>
          <div class="users-follow-list">
            <%= render @users %>
          </div>
          <div class="pagination-wrapper">
            <%= will_paginate %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>