config/routes.rb
Rails.application.routes.draw do

  # get 'password_resets/new'
  #
  # get 'password_resets/edit'

  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_assets.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" integrity="sha256-zIG416V1ynj3Wgju/scU80KAEWOsO5rRLfVyRDuOv7Q=" crossorigin="anonymous" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js" integrity="sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9" crossorigin="anonymous"></script>

app/views/layouts/_header.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to(root_path, id: "logo", class: "navbar-item") do %>
      <span class="logo-triangle"></span>
      <span>My Sample App</span>
      <% end %>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-menu">
      <div class="navbar-end">

        <%= link_to(root_path, class: "navbar-item") do %>
        <span class="icon has-text-primary"><i class="fas fa-home"></i></span>
        <span>Home</span>
        <% end %>

        <%= link_to(about_path, class: "navbar-item") do %>
        <span class="icon has-text-success"><i class="fas fa-info-circle"></i></span>
        <span>About</span>
        <% end %>

        <%= link_to(help_path, class: "navbar-item") do %>
        <span class="icon has-text-info"><i class="fas fa-question-circle"></i></span>
        <span>Help</span>
        <% end %>

        <%= link_to(contact_path, class: "navbar-item") do %>
        <span class="icon has-text-warning"><i class="fas fa-envelope"></i></span>
        <span>Contact</span>
        <% end %>

        <% if logged_in? %>
          <%= link_to(users_path, class: "navbar-item") do %>
          <span class="icon has-text-danger"><i class="fas fa-users"></i></span>
          <span>Users</span>
          <% end %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a href="#" class="navbar-link">
              <span class="icon has-text-orange"><i class="fas fa-user"></i></span>
              <span>Account</span>
            </a>
            <div id="moreDropdown" class="navbar-dropdown">

              <%= link_to(current_user, class: "navbar-item") do %>
              <span class="icon has-text-orange"><i class="fas fa-address-card"></i></span>
              <span>Profile</span>
              <% end %>

              <hr class="navbar-divider">

              <%= link_to(logout_path, method: :delete, class: "navbar-item") do %>
              <span class="icon has-text-orange"><i class="fas fa-sign-out-alt"></i></span>
              <span>Log out</span>
              <% end %>

            </div>
          </div>
        <% else %>
          <%= link_to(login_path, class: "navbar-item") do %>
          <span class="icon has-text-orange"><i class="fas fa-sign-in-alt"></i></span>
          <span>Log in</span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/assets' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <section class="section hero is-fullheight">
      <div class="hero-body">
        <div class="container">
          <%= render 'shared/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </section>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>